version: '3.8'

services:
  shift-auth-redis:
    image: redis:latest
    container_name: shift-auth-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # === PROD База данных PostgreSQL ===
  sift-db:
    image: postgres:16
    container_name: shift-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: DATABASE_PASSWORD
      POSTGRES_DB: shift_db
      POSTGRES_PORT: 5432
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # === TEST База данных для тестов ===
  shift-test-db:
    image: postgres:16
    container_name: shift-test-db
    environment:
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: shift_test_db
      POSTGRES_PORT: 5432
    ports:
      - "6544:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
  test_postgres_data: