"""create user table

Revision ID: 06a6bdc5f980
Revises: 1a22b46ea5e9
Create Date: 2025-06-21 13:38:29.854941

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06a6bdc5f980"
down_revision: Union[str, None] = "1a22b46ea5e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
