"""upgrade salary

Revision ID: 0d32e2a6ac19
Revises: 8dcf7b38e0ca
Create Date: 2025-06-29 15:19:09.097932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d32e2a6ac19'
down_revision: Union[str, None] = '8dcf7b38e0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salary_increase', 'reasons_increase',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salary_increase', 'reasons_increase',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
