"""update position

Revision ID: 1ac37144ac4f
Revises: df933cad3bd0
Create Date: 2025-06-21 14:52:15.643751

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ac37144ac4f"
down_revision: Union[str, None] = "df933cad3bd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "position",
        "min_salary",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=7, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "position",
        "max_salary",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=7, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "position",
        "max_salary",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "position",
        "min_salary",
        existing_type=sa.Numeric(precision=7, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
