"""upgrate numeric field

Revision ID: 6aa05d01bd63
Revises: b047eb614c1d
Create Date: 2025-06-27 05:51:17.538438

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aa05d01bd63"
down_revision: Union[str, None] = "b047eb614c1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "position",
        "min_salary",
        existing_type=sa.NUMERIC(precision=7, scale=2),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "position",
        "max_salary",
        existing_type=sa.NUMERIC(precision=7, scale=2),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "user_position",
        "salary",
        existing_type=sa.NUMERIC(precision=7, scale=2),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_position",
        "salary",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.NUMERIC(precision=7, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "position",
        "max_salary",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.NUMERIC(precision=7, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "position",
        "min_salary",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.NUMERIC(precision=7, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
