"""upgrate user_position

Revision ID: 7af61d7a351a
Revises: 6aa05d01bd63
Create Date: 2025-06-28 17:54:17.831639

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7af61d7a351a"
down_revision: Union[str, None] = "6aa05d01bd63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_position",
        sa.Column("assigned_salary", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.drop_column("user_position", "salary")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_position",
        sa.Column(
            "salary",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user_position", "assigned_salary")
    # ### end Alembic commands ###
