"""upgrade salary

Revision ID: 8dcf7b38e0ca
Revises: f40d16bf013a
Create Date: 2025-06-29 15:17:46.773401

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dcf7b38e0ca"
down_revision: Union[str, None] = "f40d16bf013a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salary_increase", sa.Column("reasons_increase", sa.Text(), nullable=True)
    )
    op.alter_column(
        "salary_increase", "motivation_decision", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salary_increase",
        "motivation_decision",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.drop_column("salary_increase", "reasons_increase")
    # ### end Alembic commands ###
