"""Initial schema

Revision ID: 9bc385d3fbd6
Revises: 
Create Date: 2025-06-30 05:41:47.121272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc385d3fbd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('min_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('hash_password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_position',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.BIGINT(), nullable=True),
    sa.Column('assigned_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('assigned_at', sa.Date(), nullable=False),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_increase',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_position_id', sa.BIGINT(), nullable=False),
    sa.Column('requested_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('request_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONSIDER', 'APPROVED', 'PARTIALLY_APPROVED', 'REJECTED', name='review_status_type'), nullable=False),
    sa.Column('reasons_increase', sa.Text(), nullable=False),
    sa.Column('motivation_decision', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_position_id'], ['user_position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_increase')
    op.drop_table('user_position')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('position')
    # ### end Alembic commands ###
