"""update гыук_position

Revision ID: cf181fca8a59
Revises: 1ac37144ac4f
Create Date: 2025-06-21 14:54:30.312223

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf181fca8a59"
down_revision: Union[str, None] = "1ac37144ac4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_position",
        sa.Column("salary", sa.Numeric(precision=7, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_position", "salary")
    # ### end Alembic commands ###
