"""create table position and user_position

Revision ID: df933cad3bd0
Revises: b0f492c57d54
Create Date: 2025-06-21 14:45:08.899862

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df933cad3bd0"
down_revision: Union[str, None] = "b0f492c57d54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("min_salary", sa.Float(), nullable=False),
        sa.Column("max_salary", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user_position",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=True),
        sa.Column("position_id", sa.BIGINT(), nullable=True),
        sa.Column("assigned_at", sa.Date(), nullable=False),
        sa.Column("removed_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["position_id"], ["position.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_position")
    op.drop_table("position")
    # ### end Alembic commands ###
