"""salary

Revision ID: f40d16bf013a
Revises: f9d1ea01478b
Create Date: 2025-06-29 07:17:32.457535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40d16bf013a'
down_revision: Union[str, None] = 'f9d1ea01478b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_increase',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_position_id', sa.BIGINT(), nullable=False),
    sa.Column('requested_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('request_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONSIDER', 'APPROVED', 'PARTIALLY_APPROVED', 'REJECTED', name='review_status_type'), nullable=False),
    sa.Column('motivation_decision', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_position_id'], ['user_position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_increase')
    # ### end Alembic commands ###
